def getCategory(title, data):
    flag = 0
    if("VR") in title:
        data['SW'] = 1
        flag = 1
    if("SW") in title:
        data['SW'] = 1
        flag = 1
    if("AR") in title:
        data['SW'] = 1
        flag = 1
    if("머신러닝") in title:
        data['SW'] = 1
        flag = 1
    if("소프트") in title:
        data['SW'] = 1
        flag = 1
    if("soft") in title:
        data['SW'] = 1
        flag = 1
    if("소프트웨어") in title:
        data['SW'] = 1
        flag = 1
    if("AI") in title:
        data['SW'] = 1
        flag = 1
    if("인공지능") in title:
        data['SW'] = 1
        flag = 1
    if("코딩") in title:
        data['SW'] = 1
        flag = 1
    if("데이터") in title:
        data['SW'] = 1
        flag = 1
    if("Big") in title:
        data['SW'] = 1
        flag = 1
    if("ICT") in title:
        data['SW'] = 1
        flag = 1
    if("ict") in title:
        data['SW'] = 1
        flag = 1

    if("봉사") in title:
        data['Volunteer'] = 1
        flag = 1
    if("도우미") in title:
        data['Volunteer'] = 1
        flag = 1
    if("멘토") in title:
        data['Volunteer'] = 1
        flag = 1
    
    if("어학") in title:
        data['Language'] = 1
        flag = 1
    if("영어") in title:
        data['Language'] = 1
        flag = 1
    if("중국") in title:
        data['Language'] = 1
        flag = 1
    if("일본") in title:
        data['Language'] = 1
        flag = 1
    if("미국") in title:
        data['Language'] = 1
        flag = 1
    if("유학") in title:
        data['Language'] = 1
        flag = 1
    if("글로벌") in title:
        data['Language'] = 1
        flag = 1
    if("토익") in title:
        data['Language'] = 1
        flag = 1
    if("TOEIC") in title:
        data['Language'] = 1
        flag = 1
    
    if("에세이") in title:
        data['Social'] = 1
        flag = 1
    if("문학") in title:
        data['Social'] = 1
        flag = 1
    if("콘서트") in title:
        data['Social'] = 1
        flag = 1
    if("상담") in title:
        data['Social'] = 1
        flag = 1
    if("국제") in title:
        data['Social'] = 1
        flag = 1
    if("외교") in title:
        data['Social'] = 1
        flag = 1
    if("사회") in title:
        data['Social'] = 1
        flag = 1
    if("글쓰기") in title:
        data['Social'] = 1
        flag = 1
    if("책") in title:
        data['Social'] = 1
        flag = 1
    if("독서") in title:
        data['Social'] = 1
        flag = 1

    if("창업") in title:
        data['Startup'] = 1
        flag = 1

    if("스타트업") in title:
        data['Startup'] = 1
        flag = 1
    if("취업") in title:
        data['Job'] = 1
        flag = 1
    if("인턴") in title:
        data['Job'] = 1
        flag = 1
    if("면접") in title:
        data['Startup'] = 1
        flag = 1
    if("NCS") in title:
        data['Startup'] = 1
        flag = 1
    if("채용") in title:
        data['Job'] = 1
        flag = 1

    if("공모") in title:
        data['Competition'] = 1
        flag = 1
    if("프로젝트") in title:
        data['Competition'] = 1
        flag = 1
    if("챌린지") in title:
        data['Competition'] = 1
        flag = 1
    if("대회") in title:
        data['Competition'] = 1
        flag = 1
    
    if("서포터") in title:
        data['Supporters'] = 1
        flag = 1
    if("support") in title:
        data['Supporters'] = 1
        flag = 1
    
    if("장학") in title:
        data['Scholarship'] = 1
        flag = 1
    elif(flag==0):
        data['etc'] = 1

    return data